# Generated by Django 6.0.3 on 2026-05-18 04:56

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
        ('users', '0002_alter_company_logo_alter_companylocation_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='is_featured',
        ),
        migrations.RemoveField(
            model_name='job',
            name='salary_negotiable',
        ),
        migrations.AddField(
            model_name='job',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='job',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='jobs_job_search__684d46_gin'),
        ),
    ]
