# Generated by Django 6.0.3 on 2026-05-18 17:34

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                    CREATE EXTENSION IF NOT EXISTS pg_trgm;
                """,
            reverse_sql="""
                    DROP EXTENSION IF EXISTS pg_trgm;
                """,
        )
    ]
