# Generated by Django 6.0.3 on 2026-05-18 19:33

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_add_pg_trgm'),
        ('locations', '0004_address_deleted_at'),
        ('users', '0002_alter_company_logo_alter_companylocation_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='job',
            index=django.contrib.postgres.indexes.GinIndex(fields=['title'], name='job_title_trgm_idx', opclasses=['gin_trgm_ops']),
        ),
    ]
