# Generated by Django 6.0.3 on 2026-05-19 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_job_published_at_job_job_title_trgm_idx'),
        ('users', '0003_alter_company_logo_alter_user_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateCV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200, verbose_name='Tên CV')),
                ('file', models.FileField(upload_to='candidates/cvs/%Y/%m/', verbose_name='File CV')),
                ('candidate_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cvs', to='users.candidateprofile')),
            ],
            options={
                'verbose_name': 'CV ứng viên',
                'verbose_name_plural': 'CV ứng viên',
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Chờ xem xét'), ('reviewing', 'Đang xem xét'), ('interview', 'Phỏng vấn'), ('accepted', 'Chấp nhận'), ('rejected', 'Từ chối'), ('withdrawn', 'Ứng viên rút hồ sơ')], default='pending', max_length=20)),
                ('expected_salary', models.PositiveIntegerField(blank=True, null=True)),
                ('applied_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày nộp')),
                ('viewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Thời điểm NTD đầu tiên xem')),
                ('candidate_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='users.candidateprofile')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='jobs.job')),
                ('cv_file', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='jobs.candidatecv')),
            ],
            options={
                'verbose_name': 'Hồ sơ ứng tuyển',
                'verbose_name_plural': 'Hồ sơ ứng tuyển',
                'ordering': ['-applied_at'],
                'unique_together': {('candidate_profile', 'job')},
            },
        ),
    ]
