# Generated by Django 6.0.3 on 2026-05-18 05:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_add_search_vector_trigger'),
        ('locations', '0003_alter_country_options_rename_iso_code_country_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='locations.address'),
        ),
    ]
