# Generated by Django 6.0.3 on 2026-05-19 08:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_candidatecv_application'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatecv',
            name='file',
            field=models.FileField(upload_to='candidates/cvs/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='File CV'),
        ),
    ]
