# Generated by Django 6.0.3 on 2026-05-19 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_alter_candidatecv_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Chờ xem xét'), ('REVIEWING', 'Đang xem xét'), ('INTERVIEW', 'Phỏng vấn'), ('ACCEPTED', 'Chấp nhận'), ('REJECTED', 'Từ chối'), ('WITHDRAWN', 'Ứng viên rút hồ sơ')], default='PENDING', max_length=20),
        ),
    ]
