# Generated by Django 6.0.3 on 2026-05-23 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_alter_application_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='boost_score',
            field=models.IntegerField(default=0),
        ),
    ]
