# Generated by Django 6.0.3 on 2026-05-28 08:34
from django.contrib.postgres.operations import UnaccentExtension
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('jobs', '0007_job_boost_score'),
    ]

    operations = [
        UnaccentExtension(),
    ]
