# Generated by Django 6.0.3 on 2026-05-29 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_auto_20260528_1534'),
        ('locations', '0004_address_deleted_at'),
        ('users', '0004_alter_company_logo_alter_user_avatar'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['status', 'expired_at'], name='jobs_job_status_e045bd_idx'),
        ),
    ]
