# Generated by Django 6.0.3 on 2026-05-22 15:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('transaction_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('service_type', models.CharField(choices=[('JOB_FEATURED', 'Tin tuyển dụng nổi bật'), ('CANDIDATE_PRIORITY', 'Hồ sơ ứng viên ưu tiên')], max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('method', models.CharField(choices=[('PAYPAL', 'PayPal'), ('STRIPE', 'Stripe'), ('MOMO', 'MoMo'), ('ZALOPAY', 'ZaloPay')], max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Chờ xử lý'), ('COMPLETED', 'Thành công'), ('FAILED', 'Thất bại'), ('REFUNDED', 'Đã hoàn tiền')], default='PENDING', max_length=20)),
                ('gateway_ref', models.CharField(blank=True, help_text='Mã giao dịch từ cổng', max_length=255)),
                ('gateway_response', models.JSONField(blank=True, default=dict)),
                ('meta_data', models.JSONField(blank=True, default=dict)),
                ('currency', models.CharField(default='VND', max_length=3)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-pk'],
            },
        ),
    ]
