# Generated by Django 6.0.3 on 2026-05-23 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='gateway_response',
            new_name='metadata',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='meta_data',
        ),
    ]
