# Generated by Django 6.0.3 on 2026-05-15 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='Tên thành phố')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Mã thành phố')),
            ],
            options={
                'verbose_name': 'Thành phố',
                'verbose_name_plural': 'Thành phố',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('iso_code', models.CharField(max_length=2, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('phone_code', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'ordering': ['iso_code'],
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='Tên quận/huyện')),
                ('code', models.CharField(max_length=20, verbose_name='Mã quận/huyện')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='locations.city', verbose_name='Thành phố')),
            ],
            options={
                'verbose_name': 'Quận/Huyện',
                'verbose_name_plural': 'Quận/Huyện',
                'ordering': ['name'],
                'unique_together': {('city', 'code')},
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('street_address', models.CharField(help_text='Ví dụ: 123 Nguyễn Huệ', max_length=255, verbose_name='Địa chỉ đường/số nhà')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='addresses', to='locations.city', verbose_name='Thành phố')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='addresses', to='locations.district', verbose_name='Quận/Huyện')),
            ],
            options={
                'verbose_name': 'Địa chỉ',
                'verbose_name_plural': 'Địa chỉ',
            },
        ),
    ]
