# Generated by Django 6.0.3 on 2026-05-17 11:49

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='phone_code',
        ),
        migrations.AddField(
            model_name='country',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='flags'),
        ),
    ]
