# Generated by Django 6.0.3 on 2026-05-17 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_remove_country_phone_code_country_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['code']},
        ),
        migrations.RenameField(
            model_name='country',
            old_name='iso_code',
            new_name='code',
        ),
    ]
