# Generated by Django 6.0.3 on 2026-05-14 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_province_remove_company_address_companylocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companylocation',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='users.company'),
        ),
    ]
