# Generated by Django 6.0.3 on 2026-05-14 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_companylocation_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='province',
            name='codename',
            field=models.CharField(default='vietnam', max_length=100, unique=True),
        ),
    ]
