# Generated by Django 6.0.3 on 2026-05-15 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_province_codename'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='province',
            options={'ordering': ['codename']},
        ),
    ]
