"""
Django settings for configs project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
import os
from pathlib import Path

import environ
from django.urls import reverse_lazy

env = environ.Env(
    DEBUG=(bool, False)
)
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
environ.Env.read_env(os.path.join(BASE_DIR, '.env'))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env.str("SECRET_KEY", 'django-insecure--8)8-*828etv7e15b58uou$(a-*eycua5-i_mu$w(sy&$^v@xq')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool("DEBUG", True)

import logging
import re


class TimeOnlyColorFormatter(logging.Formatter):
    GREEN = '\033[92m'
    RESET = '\033[0m'

    def format(self, record):
        log_message = super().format(record)
        log_message = re.sub(
            r'(\[\d{2}:\d{2}:\d{2}\])',
            f'{self.GREEN}\\1{self.RESET}',
            log_message
        )
        log_message = re.sub(
            r'(\(\d+\.\d+\))',
            f'{self.GREEN}\\1{self.RESET}',
            log_message
        )

        return log_message


if DEBUG:
    LOGGING = {
        'version': 1,
        'disable_existing_loggers': False,
        'formatters': {
            'simple': {
                'format': '[{asctime}] {message}',
                'style': '{',
                'datefmt': '%H:%M:%S',
            },
            'time_color_format': {
                '()': TimeOnlyColorFormatter,
                'format': '[{asctime}] {message}',
                'style': '{',
                'datefmt': '%H:%M:%S',
            },
        },
        'handlers': {
            'console': {
                'level': 'DEBUG',
                'class': 'logging.StreamHandler',
                'formatter': 'simple',
            },
            'console_sql': {
                'level': 'DEBUG',
                'class': 'logging.StreamHandler',
                'formatter': 'time_color_format',
            },
        },
        'loggers': {
            'django.db.backends': {
                'handlers': ['console_sql'],
                'level': 'DEBUG',
                'propagate': False,
            },
        },
    }

ALLOWED_HOSTS = ['*']

DEFAULT_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.postgres',
    'django.contrib.humanize'
]

THIRD_PARTY_APPS = [
    "rest_framework",
    "oauth2_provider",
    'drf_spectacular',
    'corsheaders',
    'cloudinary_storage',
    'cloudinary',
    'django_celery_beat',
]

SELF_APPS = [
    'apps.users',
    'apps.jobs',
    'apps.payments',
    'apps.locations',
    'apps.notifications',
    'apps.reports'
]

INSTALLED_APPS = DEFAULT_APPS + THIRD_PARTY_APPS + SELF_APPS

AUTH_USER_MODEL = 'users.User'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'apps.users.auth.CachedOAuth2Authentication',
        # 'oauth2_provider.contrib.rest_framework.OAuth2Authentication',
    ),
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'My API',
    'DESCRIPTION': 'API description',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
}

OAUTH2_PROVIDER = {
    "ACCESS_TOKEN_EXPIRE_SECONDS": env.int("ACCESS_TOKEN_EXPIRE_SECONDS", 36000),
    "REFRESH_TOKEN_EXPIRE_SECONDS": env.int("REFRESH_TOKEN_EXPIRE_SECONDS", 86400),
    "ROTATE_REFRESH_TOKEN": True,
    "SCOPES": {"read": "Read scope", "write": "Write scope"},
}

CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": env.str("REDIS_URL"),
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
            "SOCKET_CONNECT_TIMEOUT": 5,
            "SOCKET_TIMEOUT": 5,
            "RETRY_ON_TIMEOUT": True,
            "MAX_CONNECTIONS": 1000,
            "CONNECTION_POOL_KWARGS": {"max_connections": 100},
        },
        "KEY_PREFIX": "job-platform",
        "TIMEOUT": 300,
    }
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'configs.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'configs.wsgi.application'

# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': env.str("DB_NAME", "job_platform_db"),
        'USER': env.str("DB_USER", "postgres"),
        'PASSWORD': env.str("DB_PASSWORD", "123456"),
        'HOST': env.str("DB_HOST", "localhost"),
        'PORT': env.int("DB_PORT", 5432)
    }
}

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTHENTICATION_BACKENDS = [
    'common.backends.EmailOrUsernameModelBackend',
    'django.contrib.auth.backends.ModelBackend',
]

CLOUDINARY_STORAGE = {
    'CLOUD_NAME': env('CLOUD_NAME'),
    'API_KEY': env('CLOUD_API_KEY'),
    'API_SECRET': env('CLOUD_API_SECRET'),
    'UNSIGNED_PRESET': None,
    'ACCESS_MODE': 'public',
    'MAGIC_FILE_PATH': 'magic',
}

SUPABASE_ACCESS_KEY = env.str("SUPABASE_ACCESS_KEY")
SUPABASE_SECRET_KEY = env.str("SUPABASE_SECRET_KEY")
SUPABASE_BUCKET = env.str("SUPABASE_BUCKET")
SUPABASE_PROJECT_ID = env.str("SUPABASE_PROJECT_ID")
AWS_S3_FILE_OVERWRITE = False
AWS_DEFAULT_ACL = "public-read"

SUPABASE_STORAGE = {
    "BACKEND": "storages.backends.s3boto3.S3Boto3Storage",
    "OPTIONS": {
        "access_key": SUPABASE_ACCESS_KEY,
        "secret_key": SUPABASE_SECRET_KEY,
        "bucket_name": SUPABASE_BUCKET,
        "endpoint_url": f"https://{SUPABASE_PROJECT_ID}.storage.supabase.co/storage/v1/s3",
        "file_overwrite": AWS_S3_FILE_OVERWRITE,
        "default_acl": AWS_DEFAULT_ACL,
        "querystring_auth": False,
        "custom_domain": f"{SUPABASE_PROJECT_ID}.supabase.co/storage/v1/object/public/{SUPABASE_BUCKET}"
    },
}

STORAGES = {
    "default": SUPABASE_STORAGE,
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
    },
}

CLIENT_ID = env.str("CLIENT_ID")
CLIENT_SECRET = env.str("CLIENT_SECRET")

TOKEN_CACHING_SECONDS = env.int("TOKEN_CACHING_SECONDS", 600)

JOB_EXPIRE_SECONDS = env.int("JOB_EXPIRE_SECONDS", 120)
JOB_DRAFT_EXPIRE_SECONDS = JOB_EXPIRE_SECONDS / 2
JOB_PAGE_SIZE = env.int("JOB_PAGE_SIZE", 20)
JOB_MAX_PAGE_SIZE = env.int("JOB_MAX_PAGE_SIZE", 100)

CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True

CELERY_BROKER_URL = env.str("CELERY_BROKER_URL")
CELERY_RESULT_BACKEND = env.str("CELERY_RESULT_BACKEND")
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers:DatabaseScheduler'

STRIPE_PUBLIC_KEY = env.str("STRIPE_PUBLIC_KEY")
STRIPE_SECRET_KEY = env.str("STRIPE_SECRET_KEY")
STRIPE_WEBHOOK_SECRET = env.str("STRIPE_WEBHOOK_SECRET")

CACHE_TTL = 300

GOTIFY_URL = f"http://localhost:{env.str("GOTIFY_PORT", "8082")}/"
GOTIFY_USER = env.str("GOTIFY_USER")
GOTIFY_PASSWORD = env.str("GOTIFY_PASSWORD")
