# Generated by Django 6.0.3 on 2026-05-24 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gotifyapplication',
            name='client_token',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
