# Generated by Django 6.0.3 on 2026-05-24 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_gotifyapplication_client_token'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gotifyapplication',
            old_name='client_token',
            new_name='basic_token',
        ),
    ]
