# Generated by Django 6.0.3 on 2026-05-24 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_rename_client_token_gotifyapplication_basic_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gotifyapplication',
            name='gotify_user_id',
        ),
    ]
